DFE-Digital/fh-referral-ui

fh-referral-ui.sln
src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboard.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboardDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/Vcs/ShowReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/Vcs/ShowReferralSummary.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Services/Api/ReferralClientService.cs
src/FamilyHubs.ReferralUi.Ui/appsettings.Development.json
tests/FamilyHubs.ReferralUi.UnitTests/Services/BaseClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingReferralClientService.cs

Replaced Common Project with FamilyHubs.ServiceDirectory.Shared NuGet Package

Replaced Common Project with FamilyHubs.ServiceDirectory.Shared NuGet Package

---

src/FamilyHubs.ReferralUi.Ui/.dockerfile

Lastest Docker file

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/appsettings.json
tests/FamilyHubs.ReferralUi.UnitTests/Services/BaseClientService.cs

Updated FamilyHubs.ServiceDirectory.Shared to the latest version

Updated FamilyHubs.ServiceDirectory.Shared to the latest version

---

src/FamilyHubs.ReferralUi.Ui/.dockerfile

Docker file update

---

src/FamilyHubs.ReferralUi.Ui/appsettings.json

appsettings fix

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResultsOld.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Services/Api/LocalOfferClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingLocalOfferClientService.cs

Upgrade FamilyHubs.ServiceDirectory.Shared to latest version

Upgrade FamilyHubs.ServiceDirectory.Shared to latest version

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ConnectFamilyToServiceStart.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/PersonalDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Search.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml.cs

Updated Professional Journey to the latest to the latest prototype
Issue of returning to a page, and updating to use redis cache still to be done

Updated professional Journey

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Services/Api/OpenReferralOrganisationClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/LocalOfferResultsPage.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingOpenReferralOrganisationClientService.cs

Fixed Categories

---

src/FamilyHubs.ReferralUi.Ui/appsettings.json
src/FamilyHubs.ReferralUi.Ui/libman.json

Added Cache Connection string

---

src/FamilyHubs.ReferralUi.Ui/Extensions/ServiceCollectionExtensions.cs
src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Infrastructure/Configuration/ApiOptions.cs
src/FamilyHubs.ReferralUi.Ui/Pages/Index.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ConnectFamilyToServiceStart.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Program.cs
src/FamilyHubs.ReferralUi.Ui/appsettings.json

Move Sign In Page to a more sensible Place
Remove das http
Upgrade FH Shared NuGet Package

Move Sign In Page to a more sensible Place

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Pages/Index.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ConnectFamilyToServiceStart.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Search.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml.cs

Moved Sign In Page to a more sensible place

Moved Sign In Page to a more sensible place

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/appsettings.json

FHG-1297 Enable / Disable Referral

FHG-1297 Enable / Disable Referral

---

src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Header.cshtml

FHG-1409 - Removed the sign out link to match the new branding design

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

https://dfedigital.atlassian.net/browse/FHG-537?atlOrigin=eyJpIjoiNWU2NDMyZjMyYjk3NDcyNTljNDIyM2VkNDAwNWMzNGEiLCJwIjoiaiJ9

Added error message for when no search results found

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Services/RedisCacheService.cs
src/FamilyHubs.ReferralUi.Ui/appsettings.json

Timeout setting is being set as 30min in all UI's
https://dfedigital.atlassian.net/browse/FHG-731?atlOrigin=eyJpIjoiOTM2Y2E2MGFhNDg5NGZiYzk3ZmJjMjVjOGY3Y2EyNWUiLCJwIjoiaiJ9

Added timeout settings for redis cache

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs

https://dfedigital.atlassian.net/browse/FHG-1397?atlOrigin=eyJpIjoiNTYzNDFkMzExZjM2NDc0OGE3ZmEwMzFlOTJhZjNlMTQiLCJwIjoiaiJ9

Added contact details in service details page

---

fh-referral-ui.sln
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Search.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Header.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Layout.cshtml
tests/cypress/e2e/fhg1032_nosearchresults.feature
tests/cypress/e2e/fhg1032_nosearchresults.js
tests/cypress/e2e/searchresults.feature
tests/cypress/e2e/searchresults.js
tests/cypress/e2e/searchresultsdetails.js
tests/fhg1042-filterbycategory.feature
tests/fhg1042-filterbycategory.js
tests/fhg1088-showfilteroption.feature
tests/fhg1088-showfilteroption.js
tests/fhg1326_dfebrandingheader.feature
tests/fhg1326_dfebrandingheader.js
tests/fhg1397_PhoneEmailAddressWebsite.feature
tests/fhg1397_PhoneEmailAddressWebsite.js
tests/fhg816_multiplefiltersselected.feature
tests/fhg816_multiplefiltersselected.js

Added missing tests. Updated a few failing tests.
[https://dfedigital.atlassian.net/jira/software/c/projects/FHG/boards/157?modal=detail&selectedIssue=FHG-571](https://dfedigital.atlassian.net/jira/software/c/projects/FHG/boards/157?modal=detail&selectedIssue=FHG-571)

Have gone through the board and added missing tests

---

src/FamilyHubs.ReferralUi.Ui/styles/scss/_global.scss
src/FamilyHubs.ReferralUi.Ui/styles/scss/pages/ServiceFilter.scss
src/FamilyHubs.ReferralUi.Ui/wwwroot/css/application.css

1395- added the filter css to the referal-ui

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ConfirmReferral.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboard.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboard.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboardDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboardDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/SignIn.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/appsettings.json
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/LocalOfferResultsPage.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/BaseClientService.cs

Added Referral Edit

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Security/SecurityHeaders.cs
src/FamilyHubs.ReferralUi.Ui/StartupExtensions.cs

https://dfedigital.atlassian.net/browse/FHG-1723?atlOrigin=eyJpIjoiYWJjZjA3NGRhMzAxNDE4ZmJiOTRjZjA4YTZlYzE2M2MiLCJwIjoiaiJ9

Added http security headers

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml.cs

Referral Bug Fix

---

src/FamilyHubs.ReferralUi.Ui/Models/HeaderViewModel.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboard.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboard.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboardDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ReferralDashboardDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Header.cshtml

Fixed Referral Bug

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

Fixed passing service ID in any format

Fixed passing service ID in any format

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml

Fixes html markup issue

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs

https://dfedigital.atlassian.net/browse/FHG-1764?atlOrigin=eyJpIjoiNWNkMzY0ZjBmYjU2NDViMmFjZjQ4MjIyMjRkNDU5NmQiLCJwIjoiaiJ9

Sorted pagination

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
tests/cypress/e2e/fhg1088-showfilteroption.feature

Return show/hide filters on mobile

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

Button brought back

---

src/FamilyHubs.ReferralUi.Ui/Services/Api/LocalOfferClientService.cs

Fixes URL for getting services

Fixes URL for getting services

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml

FHG-1778 Bug Fix
At the moment each table row (Phone, Email, Address, Website) is always printed. Needs to be made conditional i.e. only print Website if it exists in data model of that service. The same for the address, there is a line being printed with just comma. Also needs to be conditional.

FHG-1778 Bug Fix

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml

FHG-2096 Bug Fix
Age range - showing as 0-127 years old instead of 0 to 25+

FHG-2096 Bug Fix

---

src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Footer.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Layout.cshtml

FHG-1783 - Feedback link added

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Termsandcondition.cshtml

FHG-1751 - T & Cs added

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Contactus.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Footer.cshtml

FHG-1749 - Contact us page

---

src/FamilyHubs.ReferralUi.Ui/Pages/Index.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Accessibility.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Contactus.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Cookies.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Search.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Termsandcondition.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Layout.cshtml

FHG-1114 - accessibility and SEO scores brought up to 100% on all pages

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

Accessibility with Axe tool. One issue found and fixed.

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

https://dfedigital.atlassian.net/browse/FHG-2146?atlOrigin=eyJpIjoiMzhkMzcxMDAzYWQ3NGI0M2E5YjNiMjBlNjQ3NTg0NjIiLCJwIjoiaiJ9

Corrected age filter display when all ages selected

---

src/FamilyHubs.ReferralUi.Ui/Security/SecurityHeaders.cs

Security Header Update

---

src/FamilyHubs.ReferralUi.Ui/Security/SecurityHeaders.cs

Updated Security Headers

---

src/FamilyHubs.ReferralUi.Ui/Pages/Error/404.cshtml

Added the correct content to 404 error page
https://dfedigital.atlassian.net/browse/FHG-1908

fh-1908:  Added 404 content

---

src/FamilyHubs.ReferralUi.Ui/FamilyHubs.ReferralUi.Ui.csproj
src/FamilyHubs.ReferralUi.Ui/Models/ConnectWizzardViewModel.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/CheckReferralDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ConnectFamilyToServiceStart.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Consent.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/ContactDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/FamilyContact.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/PersonalDetails.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Safeguarding.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/WhySupport.cshtml.cs
src/FamilyHubs.ReferralUi.Ui/Services/IRedisCacheService.cs
src/FamilyHubs.ReferralUi.Ui/Services/RedisCacheService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/BaseProfessionalReferralPage.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingCheckReferralDetails.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingConnectFamilyToServiceStartModel.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingConsent.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingContactDetails.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingFamilyContact.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingSafeguarding.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingWhySupport.cs

FHG-1982 / FHG-2049 replace url Params with Redis cache when using the connect wizard
Added Unit Tests

FHG-1982 replace url Params with Redis cache

---

src/FamilyHubs.ReferralUi.Ui/Services/Api/LocalOfferClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingLocalOfferClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingPostcodeLocationClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingReferralClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingTokenService.cs

FHG-2049 add unit test 2

---

src/FamilyHubs.ReferralUi.Ui/Pages/Error/404.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/Contactus.cshtml

FHG-1749 - fix. Also made a small fix to 404

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml

Fixes Categories Display
https://dfedigital.atlassian.net/browse/FHG-2370

Fixes Categories Display

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml
src/FamilyHubs.ReferralUi.Ui/Services/IRedisCacheService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/BaseProfessionalReferralPage.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingCheckReferralDetails.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingSignIn.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingAuthService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingCurrentUserService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/WhenUsingRedisCacheService.cs

FHG-2049 v4 add unit tests

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferDetail.cshtml.cs
tests/FamilyHubs.ReferralUi.UnitTests/Pages/ProfessionalReferral/WhenUsingLocalOfferDetail.cs

FHG-2371 Fixed prepending web site

FHG-2371 Fixed prepending of web site

---

src/FamilyHubs.ReferralUi.Ui/Pages/Index.cshtml
src/FamilyHubs.ReferralUi.Ui/Pages/Shared/_Layout.cshtml
tests/cypress/e2e/startnow.feature
tests/cypress/e2e/startnow.js

Fixed the title issue
https://dfedigital.atlassian.net/browse/FHG-2414

FHG-2414:Fixed the Title issue

---

src/FamilyHubs.ReferralUi.Ui/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
tests/cypress/e2e/fhg543_filterbylanguage.feature
tests/cypress/e2e/fhg543_filterbylanguage.js

https://dfedigital.atlassian.net/browse/FHG-2453?atlOrigin=eyJpIjoiMTVkNjlmYTdjMWRkNDY4YmE5NDgzMzYyMGJkNTUxMmEiLCJwIjoiaiJ9
Only added a particular language in the List<SelectListItem Languages>, so no unit tests needed.

FHG-2453/Added language Somali

---

src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ConsentShutter.cshtml

Update content to match v9 of the prototype.

FHG-2853 professional form: can't connect family

---

src/FamilyHubs.Referral.Core/Models/ConnectionRequestModel.cs
src/FamilyHubs.Referral.Core/ValidationAttributes/UKGdsPostcodeAttribute.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Consent.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactDetails.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Email.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Email.cshtml.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Letter.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Letter.cshtml.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Safeguarding.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/SupportDetails.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/SupportDetails.cshtml.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Telephone.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/Text.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/WhySupport.cshtml
src/FamilyHubs.Referral.Web/Pages/Shared/ProfessionalReferralModel.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ValidationAttributes/UKGdsPostcodeAttributeTests.cs
tests/FamilyHubs.ReferralUi.UnitTests/Infrastructure/DistributedCache/ReferralDistributedCacheTests.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/BaseProfessionalReferralPage.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingConsent.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingContactDetails.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingEmail.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingLetter.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSafeguardingModel.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingSupportDetails.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingTelephone.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingText.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingWhySupport.cs

Also includes:
* open safeguarding link in new tab
* don't pass service name through the journey as a query parameter

FHG-2878 Letter page

---

src/FamilyHubs.Referral.Web/stubUsers.json

Also:
* have a stub user for each type of role
* use latest roles and general stub user updates

Fix name claim on stub users

---

src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/WhySupportContent.cshtml
src/FamilyHubs.Referral.Web/Pages/sign-out/Index.cshtml
src/FamilyHubs.Referral.Web/Pages/sign-out/Index.cshtml.cs
src/FamilyHubs.Referral.Web/appsettings.json

Updates the content on the reason for reequest page.
Also includes:
* clear down journey cache when user signs out
* set manage account link

FHG-3728, 3729, 3840, 3842 Update reason for connection content + misc

---

src/FamilyHubs.Referral.Core/ApiClients/IdamsClientException.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/ClientHelper.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingIdamsClient.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingOrganisationClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingPostcodeLocationClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingReferralClientService.cs

Added additional unit tests

---

src/FamilyHubs.Referral.Core/ApiClients/ReferralClientService.cs
src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj
src/FamilyHubs.Referral.Core/Helper/EncryptionHelper.cs
src/FamilyHubs.Referral.Web/FamilyHubs.Referral.Web.csproj
src/FamilyHubs.Referral.Web/StartupExtensions.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingReferralClientService.cs

Added Encryption of Referral Recipient

Added Encryption of Referral Recipient

---

src/FamilyHubs.Referral.Core/ConnectTelemetryPiiRedactor.cs
src/FamilyHubs.Referral.Web/StartupExtensions.cs
tests/FamilyHubs.ReferralUi.UnitTests/WhenUsingConnectTelemetryPiiRedactor.cs

Redact PII info from Application Insight data

Redact PII info from Application Insight data

---

src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj
src/FamilyHubs.Referral.Web/FamilyHubs.Referral.Web.csproj
tests/FamilyHubs.ReferralUi.UnitTests/FamilyHubs.ReferralUi.UnitTests.csproj

Upgrade FamilyHubs.ServiceDirectory.Shared removing Redis

Upgrade FamilyHubs.ServiceDirectory.Shared removing Redis

---

src/FamilyHubs.Referral.Core/ConnectTelemetryPiiRedactor.cs

ConnectTelemetryPiiRedactor Changes

ConnectTelemetryPiiRedactor Changes

---

src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj
tests/FamilyHubs.ReferralUi.UnitTests/FamilyHubs.ReferralUi.UnitTests.csproj

Update shared kernel with a typo fix for an idams endpoint address

---

src/FamilyHubs.Referral.Web/Pages/terms-of-use/Index.cshtml

FHG-4541 - Update Agree Terms of Use (as per prototype)

FHG-4541 - Update Agree Terms of Use

---

src/FamilyHubs.Referral.Web/Pages/privacy/Index.cshtml

FHG-4620 content changes

---

README.md
src/FamilyHubs.Referral.Web/Pages/privacy/Index.cshtml
src/FamilyHubs.Referral.Web/Pages/terms-and-conditions/Index.cshtml

Includes:
* [FHG-4650 Updating data protection act link on Connect T&Cs](https://github.com/DFE-Digital/fh-referral-ui/pull/278)
* [FHG-4620 content changes](https://github.com/DFE-Digital/fh-referral-ui/pull/277)

Release (22/11/2023)

---

.gitignore
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/CheckDetails.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/CheckDetails.cshtml.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactDetails.cshtml
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/ContactDetails.cshtml.cs
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferDetail.cshtml
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingContactDetails.cs

We are replacing duplicated components with reusable ones to reduce complexity and follow GDS technical standards.
- Use `<summary-list>` reusable component in `CheckDetails`
- Use `Checkbox Custom` reusable full page component in `ContactDetails`
[FHG-4916](https://dfedigital.atlassian.net/browse/FHG-4916?atlOrigin=eyJpIjoiNzIyMjlhYzczNGJhNGQ4OWIxZGFjZDRhNDc3ZTUyMDIiLCJwIjoiaiJ9)

refactor/FHG-4916 - Replace Legacy Functionality with Common Components

---

src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj
src/FamilyHubs.Referral.Web/Pages/ProfessionalReferral/LocalOfferResults.cshtml.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/ClientHelper.cs
tests/FamilyHubs.ReferralUi.UnitTests/Core/ApiClients/WhenUsingOrganisationClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Services/BaseClientService.cs
tests/FamilyHubs.ReferralUi.UnitTests/Web/Pages/ProfessionalReferral/WhenUsingLocalOfferDetail.cs

Update shared libs

---

src/FamilyHubs.Referral.Core/FamilyHubs.Referral.Core.csproj

Fix login when email contains special characters
https://github.com/DFE-Digital/fh-shared-kernel/pull/67

Upgrade shared kernel
